### ISSUE TITLE
Tests never really quit

### ISSUE THREAD

**Issue by Anna-Livia** [openfisca/tracker#7]
As a developer, when I run `make test`, I expect the tests process to stop when all the tests are OK.
However, the tracker tests never quit. I have to manually (ctrl + c) stop them.

This is due to the timer.

Two solution : 
- Add a method to quit the timer (proposed by @sandcha)
```
we can add this code and call stop_test(tracker):

    def stop_test(tracker):
        def stop_timer(tracker):
            return
        tracker.stop_timer = types.MethodType(stop_timer, PiwikTracker)
```

- Only start the timer when at least 1 request is waiting to be sent.

**Comment by sandcha** [comment]
Besides, if Ctrl-C works to stop `make test` with `Python 3.5.5`, it doesn't seem to affect it with `Python 2.7.15` 🤔
